### ISSUE TITLE
Add support for MudBlazor 7

### ISSUE THREAD

**Issue by jbartula** [biegehydra/EasyCsv-Dotnet#5]
With MudBlazor 7 there is a problem with the UI component:

System.TypeLoadException: Could not load type 'MudBlazor.MudChip' from assembly 'MudBlazor, Version=7.6.0.0, Culture=neutral, PublicKeyToken=null'.
at EasyCsv.Components.CsvFileInput.<BuildRenderTree>b__0_2(RenderTreeBuilder __builder2)

https://github.com/MudBlazor/MudBlazor/issues/8447

**Comment by entech-trice** [comment]
Just ran into this same issue. Were you able to resolve? What's interesting is that this works locally for me, but not on the server after I deploy.

**Comment by jbartula** [comment]
No. The Author of this package needs to update it for the breaking changes in MudBlazor.

**Comment by biegehydra** [comment]
Will try to fix soon. Quite busy so feel free to submit a PR to speed things up

**Comment by biegehydra** [comment]
Please try version 2.0.1 and let me know if it fixes your problems
